#!/usr/bin/env python3
"""
ZackAI — Style Anchor Bento Grid (2A)
Generated by Brandmint pipeline engine.

Provider: fal
"""
import os, sys, subprocess
from dotenv import load_dotenv

load_dotenv(os.path.expanduser("~/.claude/.env"))

BRAND_NAME = "ZackAI"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "generated")
os.makedirs(OUT_DIR, exist_ok=True)

# Ensure generated scripts can import local brandmint package adapters.
BRANDMINT_REPO_ROOT = "/Volumes/madara/2026/twc-vault/01-Projects/brandmint"
if BRANDMINT_REPO_ROOT and os.path.isdir(BRANDMINT_REPO_ROOT) and BRANDMINT_REPO_ROOT not in sys.path:
    sys.path.insert(0, BRANDMINT_REPO_ROOT)

# Skill reference images directory (composition references for Nano Banana Pro)
SKILL_REF_DIR = os.path.expanduser("~/.claude/skills/brandmint/references/images")

# =============================================================================
# PROVIDER CONFIGURATION
# =============================================================================
# Supports: fal, openrouter, openai, replicate, inference
# All generation goes through core provider adapters.

PROVIDER = os.environ.get("IMAGE_PROVIDER", "fal").lower()
SUPPORTED_PROVIDERS = {"fal", "openrouter", "openai", "replicate", "inference"}
if PROVIDER not in SUPPORTED_PROVIDERS:
    print(f"WARNING: Unknown provider '{PROVIDER}', defaulting to FAL.")
    PROVIDER = "fal"

INFERENCE_ENDPOINT = "https://api.inference.sh".strip()
if INFERENCE_ENDPOINT:
    os.environ.setdefault("INFERENCE_BASE_URL", INFERENCE_ENDPOINT)
INFERENCE_APP = "".strip()
if INFERENCE_APP:
    os.environ.setdefault("INFERENCE_IMAGE_APP", INFERENCE_APP)

try:
    from brandmint.core.providers import get_provider as _bm_get_provider
except Exception as e:
    print(f"ERROR: Failed to import core provider adapters: {e}")
    sys.exit(1)

try:
    CORE_PROVIDER = _bm_get_provider(PROVIDER)
except Exception as e:
    print(f"ERROR: Provider '{PROVIDER}' is not available: {e}")
    sys.exit(1)

print(f"Using image provider: {PROVIDER.upper()}")

NEGATIVE = """scary, dark, horror, violent, sharp edges, weapons, adult themes,
clinical, cold, sterile, robotic, metallic, hard surfaces,
screen, tablet, phone, laptop, TV, monitor,
teal mint green (Bondu competitor color), Poppins font,
cartoon anime, clipart, watermark, text overlay, blurry, low resolution,
stock photo, generic, cheap, oversaturated, uncanny valley,
bear shape, teddy bear (product is round ball-shaped creature with cat ears),
  cold tech aesthetics, robot imagery, screen-heavy visuals, clinical AI diagrams, teal/mint primary (Bondu), Poppins font (Bondu)"""

# Brand logo file (for visual reference injection — empty if no logo configured)
LOGO_PATH = ""

def upload_reference(path):
    """Resolve a local reference path; provider adapters handle upload semantics."""
    if not path or not os.path.exists(path):
        return None
    return os.path.abspath(path)

_logo_url_cache = None
def get_logo_url():
    """Upload brand logo once and cache the URL for reuse."""
    global _logo_url_cache
    if _logo_url_cache:
        return _logo_url_cache
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        print(f"  Uploading brand logo: {os.path.basename(LOGO_PATH)}")
        _logo_url_cache = upload_reference(LOGO_PATH)
        return _logo_url_cache
    return None


# Product reference images (actual product photos for Nano Banana Pro accuracy)
PRODUCT_REF_PATHS = ['/Volumes/madara/2026/twc-vault/01-Projects/HeyZack/zackai-launch/beta-update/products/phantom-purple.png', '/Volumes/madara/2026/twc-vault/01-Projects/HeyZack/zackai-launch/beta-update/products/stealth-black.png', '/Volumes/madara/2026/twc-vault/01-Projects/HeyZack/zackai-launch/beta-update/products/aqua-blue.png']

_product_ref_url_cache = None
def get_product_ref_urls():
    """Upload product reference images once and cache URLs for reuse."""
    global _product_ref_url_cache
    if _product_ref_url_cache is not None:
        return _product_ref_url_cache
    _product_ref_url_cache = []
    for p in PRODUCT_REF_PATHS:
        if os.path.exists(p):
            print(f"  Uploading product ref: {os.path.basename(p)}")
            uploaded = upload_reference(p)
            if uploaded:
                _product_ref_url_cache.append(uploaded)
    return _product_ref_url_cache


# Reference image mapping: prompt ID -> composition reference filename
REF_IMAGES = {
    "2A": "ref-2A-bento-grid.jpg",
    "2B": "ref-2B-brand-seal.jpg",
    "2C": "ref-2C-logo-emboss.jpg",
    "3A": "ref-3A-capsule-collection.jpg",
    "3B": "ref-3B-hero-product.jpg",
    "3C": "ref-3C-essence-vial.jpg",
    "4A": "ref-4A-catalog-layout.jpg",
    "4B": "ref-4B-flatlay.jpg",
    "5A": "ref-5A-heritage-engraving.jpg",
    "5B": "ref-5B-campaign-grid.jpg",
    "5D": "ref-5D-engine-icons.jpg",
    "7A": "ref-7A-contact-sheet.jpg",
    "8A": "ref-8A-seeker-poster.jpg",
    "9A": "ref-9A-engine-poster.jpg",
    "10A": "ref-7A-contact-sheet.jpg",
    "10B": "ref-7A-contact-sheet.jpg",
    "10C": "ref-7A-contact-sheet.jpg",
}

# Config-driven reference image overrides
REF_OVERRIDES = {}
REF_IMAGES.update(REF_OVERRIDES)


def get_ref_image(pid):
    """Get composition reference image path for a prompt ID."""
    fname = REF_IMAGES.get(pid, "")
    if fname:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            return path
    return None


# Supplementary composition references (dynamically selected from full catalog)
SUPP_REFS = {
    "2A": ['ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg', 'ref-style-bold-portrait-grid.jpg', 'ref-tw-198-d4m1n-bonus-elysia-premium-fashion.jpg'],
    "3A": ['ref-alt-product-branding-workflow.jpg', 'ref-alt-dieline-to-3d.jpg', 'ref-alt-passport-covers.jpg'],
    "3B": ['ref-tw-220-AmirMushich-be-typography-designer-drive.jpg', 'ref-alt-passport-covers.jpg', 'ref-alt-branded-shoes.jpg'],
    "3C": ['ref-alt-passport-covers.jpg', 'ref-alt-branded-shoes.jpg', 'ref-alt-sneaker-collabs.jpg'],
    "4A": ['ref-alt-product-branding-workflow.jpg', 'ref-alt-dieline-to-3d.jpg', 'ref-alt-passport-covers.jpg'],
    "4B": ['ref-alt-boxing-gloves.jpg', 'ref-alt-passport-covers.jpg', 'ref-alt-branded-shoes.jpg'],
    "5B": ['ref-style-collage-portraits.jpg', 'ref-tw-119-AmirMushich-nano-banana-smart-prompt.jpg', 'ref-tw-122-oggii_0-gemini-nano-banana-pro-prompt.jpg'],
    "7A": ['ref-style-bold-portrait-grid.jpg', 'ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg', 'ref-tw-198-d4m1n-bonus-elysia-premium-fashion.jpg'],
    "8A": ['ref-tw-201-AmirMushich-nano-banana-smart-prompt-font.jpg', 'ref-style-bold-portrait-grid.jpg', 'ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg'],
    "9A": ['ref-tw-201-AmirMushich-nano-banana-smart-prompt-font.jpg', 'ref-alt-3d-sticker-logos.jpg', 'ref-tw-200-AmirMushich-nano-banana-smart-prompt.jpg'],
}

_supp_ref_url_cache = {}
def get_supp_ref_images(pid, limit=3):
    """Get supplementary composition reference URLs for a prompt ID.

    Uploads images on first call, caches for reuse.
    Returns list of uploaded URLs (may be empty).
    """
    if pid in _supp_ref_url_cache:
        return _supp_ref_url_cache[pid]
    urls = []
    for fname in SUPP_REFS.get(pid, [])[:limit]:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            print(f"  Uploading supp ref: {os.path.basename(path)}")
            uploaded = upload_reference(path)
            if uploaded:
                urls.append(uploaded)
    _supp_ref_url_cache[pid] = urls
    return urls


REFERENCE_POLICY = os.environ.get("BRANDMINT_REFERENCE_POLICY", "error").strip().lower()
if REFERENCE_POLICY not in {"error", "warn", "off"}:
    print(f"WARNING: Unknown BRANDMINT_REFERENCE_POLICY '{REFERENCE_POLICY}', defaulting to error.")
    REFERENCE_POLICY = "error"


def _existing_reference_paths(pid):
    """Return local reference files that should anchor a Nano Banana generation."""
    expected = []
    if pid != "2A":
        style_anchor = os.path.join(OUT_DIR, "2A-brand-kit-bento-nanobananapro-v1.png")
        if os.path.exists(style_anchor):
            expected.append(style_anchor)
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        expected.append(LOGO_PATH)
    expected.extend([p for p in PRODUCT_REF_PATHS if os.path.exists(p)])
    ref_path = get_ref_image(pid)
    if ref_path:
        expected.append(ref_path)
    for fname in SUPP_REFS.get(pid, [])[:3]:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            expected.append(path)

    deduped = []
    seen = set()
    for path in expected:
        apath = os.path.abspath(path)
        if apath in seen:
            continue
        seen.add(apath)
        deduped.append(apath)
    return deduped



def enforce_reference_payload(pid, image_urls):
    """Prevent ref-capable Nano Banana steps from silently degrading to text-only."""
    if REFERENCE_POLICY == "off":
        return
    expected = _existing_reference_paths(pid)
    provided = [url for url in (image_urls or []) if url]
    if not expected or provided:
        return

    names = ", ".join(os.path.basename(path) for path in expected[:5])
    message = (
        f"[{pid}] Reference payload missing despite available refs: {names}. "
        "This Nano Banana step would degrade to text-only generation."
    )
    if REFERENCE_POLICY == "warn":
        print(f"WARNING: {message}")
        return
    raise RuntimeError(message)


def _normalize_png_if_needed(filepath):
    """Convert JPEG/WebP/SVG payloads into PNG when output path expects PNG."""
    if not filepath.endswith(".png") or not os.path.exists(filepath):
        return
    with open(filepath, "rb") as f:
        header = f.read(64)
    if header.startswith(b"\x89PNG"):
        return

    try:
        if header[:2] == b"\xff\xd8" or header[:4] == b"RIFF":
            subprocess.run(
                ["sips", "-s", "format", "png", filepath, "--out", filepath],
                check=True,
                capture_output=True,
            )
            return

        head_text = header.decode("utf-8", errors="ignore").lstrip().lower()
        if head_text.startswith("<?xml") or "<svg" in head_text:
            tmp_svg = filepath + ".svg.tmp"
            os.replace(filepath, tmp_svg)
            try:
                subprocess.run(
                    ["rsvg-convert", "-w", "2048", "-h", "2048", "--keep-aspect-ratio", tmp_svg, "-o", filepath],
                    check=True,
                    capture_output=True,
                )
            finally:
                if os.path.exists(tmp_svg):
                    os.remove(tmp_svg)
            return
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"  WARNING: failed to normalize image payload at {filepath}: {e}")


def gen_with_provider(
    prompt,
    model,
    output_path,
    width=1024,
    height=1024,
    image_url=None,
    image_urls=None,
    negative_prompt="",
    **kwargs,
):
    """Generate with core provider adapters only."""
    if CORE_PROVIDER is None:
        return False

    primary_ref = image_url
    if primary_ref is None and isinstance(image_urls, list) and image_urls:
        primary_ref = image_urls[0]

    result = CORE_PROVIDER.generate(
        prompt=prompt,
        model=model,
        output_path=output_path,
        width=width,
        height=height,
        image_url=primary_ref,
        negative_prompt=negative_prompt,
        image_urls=image_urls,
        **kwargs,
    )
    if not (result and result.success):
        err = result.error if result else "unknown adapter error"
        print(f"  ERROR: generation failed for {model} via {PROVIDER}: {err}")
        return False

    _normalize_png_if_needed(output_path)
    if os.path.exists(output_path):
        size_kb = os.path.getsize(output_path) / 1024
        print(f"  Saved: {os.path.basename(output_path)} ({size_kb:.0f} KB)")
    return True


def gen_nano_banana(pid, slug, prompt, aspect, image_urls, seeds=(42, 137)):
    """Generate with Nano Banana Pro via unified core provider adapter path."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    enforce_reference_payload(pid, image_urls)
    
    # Parse aspect ratio to get dimensions
    aspect_dims = {"16:9": (1792, 1024), "9:16": (1024, 1792), "1:1": (1024, 1024), 
                   "3:4": (896, 1152), "4:3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-nanobananapro-{variant}.png")
        print(f"\n  [{pid}] Nano Banana Pro seed={seed} (provider: {PROVIDER})...")
        gen_with_provider(
            full_prompt,
            "nano-banana-pro",
            out_path,
            w,
            h,
            image_urls=image_urls,
            negative_prompt="",
            seed=seed,
            aspect_ratio=aspect,
            resolution="2K",
            output_format="png",
            num_images=1,
        )


PROMPT_2A = """ZackAI (Kids AI / Smart Toys / EdTech).
Act as Lead Brand Designer creating a comprehensive "Brand Identity System" presentation (Bento-Grid Layout).
Core metaphor: A warm, glowing plush friend who whispers knowledge and kindness. Mood: soft, intelligent, playful, warm, cozy, safe, glowing, curious, friendly, approachable.

Generate a single high-resolution Bento-Grid Layout board containing 6 distinct modules:

PHASE 1: VISUAL STRATEGY
1. Analyze the Brand: Archetype = "The Playful Guardian" -- Warm, playful, reassuring, parent-trustworthy.
   Visual vibe = Soft Intelligence, Approachable AI wrapped in cozy, tactile softness. Technology that feels like a hug..
   Visual territory: warm AI companion that parents trust — screen-free, multilingual, emotionally intelligent, animated LED personality.
2. Define the Palette: Muted Lilac 60% backgrounds. Cloud White 30% text/surfaces. Warm Sunset Orange 10% highlights ONLY.
   Muted Lilac #AA98D6, Cloud White #F8F6F2,
   Warm Sunset Orange #E67A2E, Soft Almond Cream #D9D3C1.
3. Select Typography: Figtree (headers, SemiBold/Bold, title case). Inter (body).

PHASE 2: THE LAYOUT
Block 1 (The Hero): High-contrast photograph of a Round, ball-shaped fluffy plush creature in Muted Lilac (#AA98D6) with pointed cat-like ears, cream/beige face with rosy cheeks, large animated blue LED eyes synced with voice/emotion/mood, small red smile, grey inner ears, hypoallergenic fur, USB-C charging resting on
soft fluffy plush fabric surface inside Cozy kids' bedroom, play corner with soft textures, warm afternoon light, family living room. Warm Warm Sunset Orange light.
Materials: soft fluffy plush fabric, hypoallergenic fur, brushed cotton, sealed rounded LED components, warm LED glow (animated eyes), USB-C charging cable, kraft paper packaging, embossed cardboard, woven label tag, recycled polyester fill, matte silicone accents, soft felt lining. Overlay "ZackAI" wordmark in
Cloud White (#F8F6F2), Figtree SemiBold, title case.
Block 2 (Social Media): Instagram Post mockup -- Muted Lilac (#AA98D6)
background with subtle pattern overlay at 5% opacity, centered text in Figtree:
"Screen-Free Playtime Companion" Warm Sunset Orange accent line below.
Block 3 (The Palette): 5 Vertical Color Swatches -- #AA98D6, #F8F6F2,
#E67A2E, #D9D3C1, #4CC8B2. Simulated HEX codes.
Block 4 (Typography Spec): "Figtree" displayed prominently. Tiny "Primary
Typeface" subtext in Inter.
Block 5 (The Sigil): A round fluffy creature silhouette with pointed cat-like ears and glowing LED eyes. Round ball body silhouette (warmth, softness, approachability), Pointed cat/fox ears (playfulness, curiosity), Glowing LED eyes (AI intelligence, emotional connection).
Block 6 (Brand DNA): Manifesto Card -- ARCHETYPE: "The Playful Guardian."
VOICE: "Warm, playful, reassuring, parent-trustworthy." POSITIONING: "For intentional parents in France who want their children aged 3-12 to learn, play, and grow through conversation rather than screens, ZackAI is the AI-powered plush companion that combines the warmth of a stuffed animal with the intelligence of a personal tutor. Unlike Bondu, which locks families into subscriptions, unlike Tonies and Yoto, which offer passive audio playback, and unlike smart speakers, which were never designed for children, ZackAI delivers adaptive, multilingual, conversational learning inside a huggable, screen-free form factor — certified safe under EU regulations, available in five bold colors led by Phantom Purple, and sold at EUR 99 with no subscription ever. ZackAI is not a gadget. It is the friend every curious child deserves.."
PILLARS: screen-free learning, emotional intelligence, multilingual play, parent trust, animated LED personality. VISUALS: "Approachable AI wrapped in cozy, tactile softness. Technology that feels like a hug.."


PHASE 3: AESTHETIC & FINISH
Soft studio lighting with Warm Sunset Orange rim accent. soft graduated shadows, no harsh edges. Quality: 8K.  Extreme attention to micro-detail: material grain, light caustics, sub-surface scattering, fiber textures.
Sharp edges, 1px Soft Almond Cream borders. Generous white space. Optimized for Kickstarter: bold hero imagery, clear product shots, campaign grid.
Atmosphere: Dribbble Popular / Behance Kids Design."""


def main():
    print("=" * 60)
    print(f"{BRAND_NAME} -- Style Anchor Bento Grid (2A)")
    print("Model: Nano Banana Pro | MUST RUN FIRST")
    print("=" * 60)

    # Upload composition reference image if available
    image_urls = []
    ref_path = get_ref_image("2A")
    if ref_path:
        print(f"\nUploading composition reference: {os.path.basename(ref_path)}")
        ref_url = upload_reference(ref_path)
        if ref_url:
            image_urls.append(ref_url)
    else:
        print("\nNo composition reference found for 2A (optional).")

    # Add brand logo as visual reference if available
    logo_url = get_logo_url()
    if logo_url:
        image_urls.append(logo_url)

    # Product reference images help the anchor stay faithful to the hero object.
    for purl in get_product_ref_urls():
        image_urls.append(purl)

    # Add supplementary composition references
    image_urls.extend(get_supp_ref_images("2A"))

    print("\n--- 2A: Brand Kit Bento Grid ---")
    gen_nano_banana("2A", "brand-kit-bento", PROMPT_2A, "16:9", image_urls)

    print("\n" + "=" * 60)
    print("  ANCHOR GENERATION COMPLETE (2A)")
    print("  This file is the STYLE ANCHOR for all subsequent generation.")
    print("=" * 60)


if __name__ == "__main__":
    main()
